spring:
  application:
    name : springbootZuul
server:
  port: 8060
eureka:
  instance:
    instance-id: zuul
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
zuul:
  routes:
    sbService:
      path: /sbService/**
      serviceId : boot-api
