spring:
  application:
    name : springbootZuul
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        application:
          name: zuul
server:
  port: 8060
zuul:
  routes:
    sbService:
      path: /sbService/**
      serviceId : boot-api
