spring:
  application:
    name : springbootRibbon
server:
  port: 8051
eureka:
  instance:
    instance-id: ribbon
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
feign:
  hystrix:
    enabled: true
