# ***************************测试配置**************************** #
# 当前激活的配置名称(请不要修改)
profile: test
# 密码加密配置
jasypt:
  encryptor:
    password: ${JASYPT_ENCRYPTOR_PASSWORD:}
# 服务器端口号
server.port: 9061
#Spring框架内部配置
spring:
  #数据源配置
  datasource:
    url: jdbc:mysql://192.168.16.172:3306/data?useUnicode=true&characterEncoding=utf-8&useSSL=false&useTimezone=true&serverTimezone=GMT%2B8
    username: ENC(WdsbLfMqOVt4fifwvlrP/g==)
    password: ENC(YAS0fQLf2HgpNwy8EosToc3pBFUyvsla)
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    #下面为连接池的补充设置，应用到上面所有数据源中
    #初始化大小，最小，最大
    initialSize: 5
    minIdle: 10
    maxActive: 100
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 30000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 100
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        application:
          name: boot
#redis配置
redisCluster:
  configKey: DEFAULT
  connectionTimeout: 4000
  soTimeout: 5000
  maxRedirections: 3000
  maxTotal: 10
  maxIdle: 5
  minIdle: 2
  maxWaitMillis: 2000
  testOnBorrow: false
  testOnReturn: false
  testWhileIdle: true
  masterIPs: 192.168.16.171:7000,192.168.16.171:7001,192.168.16.171:7002,192.168.16.172:7000,192.168.16.172:7001,192.168.16.172:7002
  password: platscan
#日志配置
logging:
  file: ./logs/${spring.application.name}-${version}-${profile}.log
  #日志级别
  level:
    org.springframework: debug
    network.spring.boot.demo: debug
config:
  ret: 123
