spring:
  application:
    name : springbootFeign
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        application:
          name: feign
server:
  port: 8050
feign:
  hystrix:
    enabled: true
