spring:
  application:
    name : springbootFeign
server:
  port: 8050
eureka:
  instance:
    instance-id: feign
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
feign:
  hystrix:
    enabled: true
